/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type Song = {
  __typename: "Song",
  song: string,
  artist: string,
  songReleaseDate: string,
  playCount: number,
  metricA: number,
  metricB: number,
  metricC?: number | null,
  metricD: number,
  metricE: number,
  metricF: number,
  metricG: number,
  metricH: number,
  metricI: number,
  metricJ: number,
  metricK: number,
  metricL: number,
  metricM: number,
  metricN: number,
  metricO: number,
  metricP: number,
  metricCi?: number | null,
};

export type GetSongsQuery = {
  getSongs?:  Array< {
    __typename: "Song",
    song: string,
    artist: string,
    songReleaseDate: string,
    playCount: number,
    metricA: number,
    metricB: number,
    metricC?: number | null,
    metricD: number,
    metricE: number,
    metricF: number,
    metricG: number,
    metricH: number,
    metricI: number,
    metricJ: number,
    metricK: number,
    metricL: number,
    metricM: number,
    metricN: number,
    metricO: number,
    metricP: number,
    metricCi?: number | null,
  } | null > | null,
};
